DROP TABLE IF EXISTS `agent`;
CREATE TABLE `agent` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(64) NOT NULL,
	PRIMARY KEY(`id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

DROP TABLE IF EXISTS `agent_relation`;
CREATE TABLE `agent_relation` (
	`parent` INTEGER NOT NULL,
	`child` INTEGER NOT NULL,
	PRIMARY KEY(`parent`),
	index(`child`)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


DROP TABLE IF EXISTS `schedule`;
CREATE TABLE `schedule` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`agentId` INTEGER NOT NULL,
	`startTime` DATETIME NOT NULL,
	`endTime` DATETIME NOT NULL,
	`head` VARCHAR(32) NOT NULL,
	`body` VARCHAR(500) NOT NULL,
	PRIMARY KEY(`id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

